spring:
    application:
        name: hello
    jpa: 
        hibernate:
            # create, create-drop, update, none
            ddl-auto: none
            # 맨 처음 실행할때 create, 그 이후엔 none으로 바꿔주기(?)
        # 콘솔 출력
        show-sql: true
        properties:
            hibernate:
                # h2
                # dialect: org.hibernate.dialect.H2Dialect
                # mariadb
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console # http://localhost:8088/h2-console 

